version: '2.1'

services:
  postgres:
    image: mdillon/postgis:9.5
    container_name: fieldsight_postgis
    restart: always
    volumes:
      - ./.backup/postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file:
      - db.txt

  mongo:
    image: mongo:3.4
    hostname: mongo
    container_name: fieldsight_mongo
    environment:
      - MONGO_DATA=/data/db
    env_file:
      - env.txt
      - db.txt
    ports:
      - 27017:27017
    restart: on-failure

  redis_main:
    image: redis:3.2
    restart: always
    container_name: fieldsight_redis_main
    ports:
      - 6379:6379
    sysctls:
      - net.core.somaxconn=2048

  redis_cache:
    image: redis:3.2
    restart: on-failure
    container_name: fieldsight_redis_cache
    ports:
      - 6380:6380
    sysctls:
        - net.core.somaxconn=2048