version: '2.1'

services:
  fieldsight:
    image: fieldsight/fieldsight:0.0.1
    restart: always
    container_name: fieldsight_web
    command: python manage.py runserver 0.0.0.0:8001
    volumes:
      - ../fieldsight/:/usr/src/data/
    ports:
      - 8001:8001
    env_file:
      - env.txt
      - db.txt

  kpi:
    image: fieldsight/kpi:0.0.1
    restart: on-failure
    container_name: fieldsight_kpi
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - env.txt
      - db.txt
    volumes:
      - ../kpi/:/srv/src/kpi/
    ports:
      - 8000:8000

  enketo:
    image: fieldsight/fieldsight_enketo:0.0.1
    restart: on-failure
    container_name: fieldsight_enketo
    command: npm start
    volumes:
      - ../enketo-express/:/srv/src/enketo_express/
    env_file:
      - env.txt
      - db.txt
    ports:
      - 8005:8005

  nginx:
    image: nginx:1.17.2-alpine
    container_name: fieldsight_nginx
    volumes:
      - ./nginxlog:/var/log/nginx/
      - ./nginx:/etc/nginx/conf.d/
    ports:
      - 80:80
      - 443:443
