version: '2.1'

services:
  fieldsight:
    image: fieldsight/fieldsight:0.0.1
    restart: always
    container_name: fieldsight_web
    command: /bin/bash ./scripts/run_kobocat.sh
    volumes:
      - ./fixes/fieldsight_settings.py:/usr/src/data/onadata/settings/fieldsight_settings.py
      - ./scripts/run_kobocat.sh:/usr/src/data/scripts/run_kobocat.sh
    ports:
      - 8001:8001
    env_file:
      - env.txt
      - db.txt

  kpi:
    image: fieldsight/kpi:0.0.1
    restart: on-failure
    container_name: fieldsight_kpi
    command: /bin/bash ./scripts/run_kpi.sh
    env_file:
      - env.txt
      - db.txt
    volumes:
      - ./fixes/local_settings.py:/srv/src/kpi/kobo/local_settings.py
      - ./log/kpi:/srv/logs
      - ./scripts/run_kpi.sh:/srv/src/kpi/scripts/run_kpi.sh
    ports:
      - 8000:8000

  enketo:
    image: fieldsight/fieldsight_enketo:0.0.1
    restart: on-failure
    container_name: fieldsight_enketo
    command: /bin/bash ./scripts/run_enketo.sh
    volumes:
      - ./scripts/run_enketo.sh:/srv/src/enketo_express/scripts/run_enketo.sh
      - ./fixes/config.json:/srv/src/enketo_express/config/config.json
    env_file:
      - env.txt
      - db.txt
    ports:
      - 8005:8005

  nginx:
    image: nginx:1.17.2-alpine
    container_name: fieldsight_nginx
    volumes:
      - ./nginxlog/:/var/log/nginx/
      - ./nginx/:/etc/nginx/conf.d/
      - ./certs/:/etc/ssl/certs/
    ports:
      - 80:80
      - 443:443
