version: '2.1'

services:
#----------------------------------------------------------------------------------------------  
#                start of backend services
#-----------------------------------------------------------------------------------------------
  postgres:
    extends: 
      file: docker-compose.backend.yaml
      service: postgres
   
  mongo:
    extends: 
      file: docker-compose.backend.yaml
      service: mongo

  redis_main:
    extends: 
      file: docker-compose.backend.yaml
      service: redis_main

  redis_cache:
    extends: 
      file: docker-compose.backend.yaml
      service: redis_cache
  #--------------------------------------------------------------------
  #               end of backend services
  #-------------------------------------------------------------------
  #-------------------------------------------------------------------
  #               start of front end services
  #--------------------------------------------------------------------
  fieldsight:
    extends: 
      file: docker-compose.frontend.yaml
      service: fieldsight
    depends_on:
      - postgres
      - mongo
      - redis_main
      - redis_cache

  kpi:
    extends: 
      file: docker-compose.frontend.yaml
      service: kpi
    links:
      - postgres
      - mongo
    depends_on:
      - postgres
      - redis_main
      - redis_cache

  enketo:
    extends: 
      file: docker-compose.frontend.yaml
      service: enketo
    depends_on:
      - postgres
      - redis_main

  nginx:
    extends: 
      file: docker-compose.frontend.yaml
      service: nginx
    depends_on:
      - enketo
      - kpi
      - fieldsight
    links:
      - enketo
      - kpi
      - fieldsight
#------------------------------------------------------------------------------------------
#                     end of frontend services
#------------------------------------------------------------------------------------------