version: '3'

services:
  fieldsight:
    image: fieldsightdocker/fieldsight_web:0.0.4
    restart: always
    hostname: kobo
    container_name: fieldsight_web
    command: /bin/bash ./scripts/run_fieldsight.sh
    volumes:
      - ./.vols/static/fieldsight/:/usr/src/data/onadata/static/
      - ./.vols/media/fieldsight/:/usr/src/data/media/
      - ./fixes/gcloud/service_account.json:/usr/src/data/service_account.json
      - ./fixes/gcloud/settings.yaml:/usr/src/data/settings.yaml
      - ./fixes/gcloud/credentials.json:/usr/src/data/credentials.json
    ports:
      - 8001:8001
    env_file:
      - env.txt
      - db.txt
    depends_on:
      - postgres
      - mongo
      - redis_main
    networks:
      fieldsight-network:
        aliases:
          - kobo
  kpi:
    image: fieldsightdocker/fieldsight-kpi:0.0.3
    restart: on-failure
    hostname: kpi
    container_name: fieldsight_kpi
    command: /bin/bash ./scripts/run_kpi.sh
    env_file:
      - env.txt
      - db.txt
    volumes:
      - ./log/kpi:/srv/logs
      - ./.vols/media/kpi/:/srv/src/kpi/media/
    ports:
      - 8000:8000
    depends_on:
      - postgres
      - mongo
      - redis_main
    networks:
      fieldsight-network:
        aliases:
          - kpi

  enketo:
    image: fieldsightdocker/fieldsight_enketo:0.0.3
    restart: on-failure
    container_name: fieldsight_enketo
    command: /bin/bash ./run_enketo.sh
    volumes:
      - ./fixes/config.json:/srv/src/enketo_express/config/config.json
    env_file:
      - env.txt
      - db.txt
    ports:
      - 8005:8005
    depends_on:
      - redis_main
      - redis_cache
    networks:
      fieldsight-network:
        aliases:
          - enketo_express

  nginx:
    image: nginx:1.17.2-alpine
    hostname: nginx
    container_name: fieldsight_nginx
    volumes:
      - ./nginxlog/:/var/log/nginx/
      - ./nginx/:/etc/nginx/conf.d/
      - ./certs/:/etc/ssl/certs/
      - ./.vols/static/:/static
      - ./.vols/media/:/media
    ports:
      - 80:80
      - 443:443
    depends_on:
      - enketo
      - kpi
      - fieldsight
    networks:
      fieldsight-network:
        aliases:
          - nginx
          - kpi.fieldsight.test
          - enketo.fieldsight.test
          - kobo.fieldsight.test

networks:
  fieldsight-network:
    driver: bridge