client_config_backend: settings
client_config:
  client_id: xxxxxx.apps.googleusercontent.com
  client_secret: xxxxxx

save_credentials: True
save_credentials_backend: file
save_credentials_file: ../drive_credentials.json

get_refresh_token: True

oauth_scope:
  - https://www.googleapis.com/auth/drive.file
  - https://www.googleapis.com/auth/drive.install